# Generated by Django 4.0.5 on 2023-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='gender_code',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='position_category',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Senior Leader', 'Senior Leader'), ('Manager/Supervisor/Superintendent', 'Manager/Supervisor/Superintendent'), ('Foreperson', 'Foreperson'), ('Individual Contributor', 'Individual Contributor')], max_length=500, null=True),
        ),
    ]
