# Generated by Django 4.0.5 on 2023-11-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0003_alter_companydata_aboriginal_peoples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_data_sizes', to='dddashboard.companyname'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_data_names', to='dddashboard.companyname'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='year_created',
            field=models.DateField(),
        ),
    ]
