# Generated by Django 4.0.5 on 2023-12-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dddashboard', '0005_alter_companydata_company_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyname',
            name='size',
        ),
    ]
